---
title: "About"
---

I am a PhD Candidate at Utrecht University (Department of Developmental Psychology) in the Netherlands with a background in social cognitive and psychometric research.\
\
My research focuses on the cognitive skills of people who grew up in adversity - for example, living in poor and violent neighborhoods. While decades of research suggest that adversity exposure typically leads to worse cognitive performance, recent work suggests that people's mental skills may actually adapt to the environmental challenges that they face.\
\
The central aim of my research is to better understand the specific cognitive processes that underlie improvements (and impairments) in performance as a result of growing up in adversity. I mainly focus on attention control and working memory, two highly related cognitive functions that are central to goal-directed behavior. I use cognitive modeling approaches to break down performance in more detail.

*This website is currently under construction, but will be completed soon*\
\
